import 'package:proconnect/domain/models/apartment.dart';
import 'package:proconnect/domain/models/condo.dart';
import 'package:proconnect/data/floor/datasource/floor_remote_data_source.dart';
import 'package:proconnect/data/apartment/datasource/apartment_remote_data_source.dart';

class SeedingService {
  final FloorRemoteDataSource _floorSource;
  final ApartmentRemoteDataSource _apartmentSource;

  SeedingService({
    required FloorRemoteDataSource floorSource,
    required ApartmentRemoteDataSource apartmentSource,
  }) : _floorSource = floorSource,
       _apartmentSource = apartmentSource;

  Future<void> seedFloorsAndApartments({
    required Condo condo,
    int floorCount = 20,
    int apartmentsPerFloor = 5,
  }) async {
    final agencyId = condo.agencyId ?? '';
    if (agencyId.isEmpty) {
      throw Exception('Condo must have an agency ID assigned to seed data.');
    }

    for (int i = 1; i <= floorCount; i++) {
      // Create Floor
      final floor = await _floorSource.createFloor(
        condominiumId: condo.id,
        agencyId: agencyId,
        floorNumber: i,
        floorName: 'Floor $i',
        totalApartments: apartmentsPerFloor,
        description: 'Auto-generated floor $i for ${condo.name}',
      );

      // Create Apartments for this floor
      for (int j = 1; j <= apartmentsPerFloor; j++) {
        final apartmentNumber = '${i}${j.toString().padLeft(2, '0')}';

        final apartment = Apartment(
          id: '', // Will be generated by datasource
          condominiumId: condo.id,
          agencyId: agencyId,
          floorId: floor.id,
          apartmentNumber: apartmentNumber,
          totalSizeSquareFeet: 850.0 + (j * 10),
          totalBedrooms: 2,
          totalBathrooms: 2,
          status: ApartmentStatus.vacant,
          furnishing: FurnishingStatus.partiallyFurnished,
          monthlyRent: 1500.0 + (i * 50),
          securityDeposit: 3000.0 + (i * 100),
          description: 'Beautiful unit $apartmentNumber on Floor $i',
        );

        await _apartmentSource.createApartment(apartment);
      }
    }
  }
}
