// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhzncHcg5Q60gjoJPlUSeYIxHOMRsy8tw',
    appId: '1:79685991906:web:552ef9ce5507fa22eacdbb',
    messagingSenderId: '79685991906',
    projectId: 'proconnectmala',
    authDomain: 'proconnectmala.firebaseapp.com',
    storageBucket: 'proconnectmala.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAiqusQWpKM9djPqJPnwriYDaprNxQBZY',
    appId: '1:79685991906:android:b65db5e37de24a4feacdbb',
    messagingSenderId: '79685991906',
    projectId: 'proconnectmala',
    storageBucket: 'proconnectmala.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuLDnewq5fe99xokh4glbkQ0fqtr2Yx5I',
    appId: '1:79685991906:ios:eda28e1746894983eacdbb',
    messagingSenderId: '79685991906',
    projectId: 'proconnectmala',
    storageBucket: 'proconnectmala.firebasestorage.app',
    iosBundleId: 'com.proconnect.proconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuLDnewq5fe99xokh4glbkQ0fqtr2Yx5I',
    appId: '1:79685991906:ios:516710c4649bb5c1eacdbb',
    messagingSenderId: '79685991906',
    projectId: 'proconnectmala',
    storageBucket: 'proconnectmala.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhzncHcg5Q60gjoJPlUSeYIxHOMRsy8tw',
    appId: '1:79685991906:web:53e2296407d62388eacdbb',
    messagingSenderId: '79685991906',
    projectId: 'proconnectmala',
    authDomain: 'proconnectmala.firebaseapp.com',
    storageBucket: 'proconnectmala.firebasestorage.app',
  );
}
